language: go
go:
  - 1.14
  - tip

os:
  - linux

matrix:
 fast_finish: true

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get -t -v ./...

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - $GOPATH/bin/goveralls -service=travis-pro -covermode=atomic

sudo: false
