language: go
go:
  - 1.14
  - tip

os:
  - linux

matrix:
 fast_finish: true

before_install:
  - go get github.com/mattn/goveralls

install:
  - git clone https://github.com/mbaynton/bot.git $GOPATH/src/github.com/go-chat-bot/bot
  - go get -t -v ./...

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - $GOPATH/bin/goveralls -service=travis-ci

sudo: false
