language: go
go:
  - 1.7.5
  - 1.8
  - tip

os:
  - linux

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - git clone git@github.com:mbaynton/bot.git $GOPATH/src/github.com/go-chat-bot/bot

script:
  - go install ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v ./...

sudo: false
