language: go
go:
  - 1.8
  - 1.9
  - tip

os:
  - linux

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - git clone https://github.com/mbaynton/bot.git $GOPATH/src/github.com/go-chat-bot/bot
  - go get -t -v ./...

script:
  - go install ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v ./...

sudo: false
