---
environment: persistent_systems_production
parameters:
  param1: value1
  param2:
    - value1
    - value2
  param3:
    param4: value1

# This node has cname helpdesk.msi. Allow ssh from linux workstations for acctadmin.
firewall_msi::rules::both:
  200 Accept ssh from linux workstations:
    proto: tcp
    dport: 22
    source: addressbook:Linux Workstations
    state: NEW
    action: accept

additional_classes:
  - aaa_msi::ldap_backup_target
  - pam_access_msi::entry::allow_techsup_all
