---
BindAddress: 127.0.0.1:8240
PuppetExecutable: ../TestFixtures/fakepuppet.sh

GenericExecTasks:
  - Name: task1
    Command: Command1
    Args:
      - "fred"
      - "tuttle"
  - Name: task2
    Command: Command2
